#!/usr/bin/env bash

curl -X POST -H 'Content-type:application/json' --data-binary '{
  "add-field":{
     "name":"rank",
     "type":"int"
  },
  "add-field":{
     "name":"qid",
     "type":"int"
   },
   "add-field":{
     "name":"query",
     "type":"string"
   },
   "add-copy-field":{
     "source":"query",
     "dest":[ "query_txt_en"]
   },
   "add-field":{
     "name":"product_id",
     "type":"string"
   },
    "add-field":{
     "name":"queryScore",
     "type":"float"
   },
    "add-field":{
     "name":"grossSales",
     "type":"float"
   },
    "add-field":{
     "name":"price",
     "type":"float"
   },
    "add-field":{
     "name":"productViewCount ",
     "type":"float"
   },
    "add-field":{
     "name":"isNew",
     "type":"float"
   },
    "add-field":{
     "name":"ItemTypeHitInFieldPercent",
     "type":"float"
   },
    "add-field":{
     "name":"S1_Deals_and_PromotionsHitInField",
     "type":"float"
   },
    "add-field":{
     "name":"BrandHitInFieldPercent",
     "type":"float"
   },
    "add-field":{
     "name":"AverageRating",
     "type":"float"
   },
    "add-field":{
     "name":"hasProductViewCnt",
     "type":"float"
   },
    "add-field":{
     "name":"hasAverageRating",
     "type":"float"
   },
    "add-field":{
     "name":"hasActualGrossSalesDollars",
     "type":"float"
   },
    "add-field":{
     "name":"ProductTypeHitInFieldPercent",
     "type":"float"
   },
    "add-field":{
     "name":"GrpNameHitInFieldPercent ",
     "type":"float"
   },
   "add-field":{
     "name":"search_count",
     "type":"int"
   },
   "add-field":{
     "name":"clicked",
     "type":"int"
   },
   "add-field":{
     "name":"add_to_bag",
     "type":"int"
   },
      "add-field":{
     "name":"checked_out",
     "type":"int"
   }
}' http://localhost:8983/solr/trainingset/schema